[package]
name = "gfxinfra"
version = "0.1.0"
authors = ["dragonelite <thubie90@live.nl>"]

[dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
dxgi-sys = "0.2.0"
d3d12-sys = "0.2.0"
dxguid-sys = "0.2.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0"
